export const events = [
    {
      id: "1",
      title: "Magical Event",
      imageUrl: "https://via.placeholder.com/150",
      date: "2023-05-01",
      location: "Hogwarts",
      organizer: "Dumbledore",
      spellCategory: "Transfiguration",
      Fee: "50",
      description: "A magical event to showcase wizardry.",
      currentParticipants: 30,
      maxParticipants: 100,
    },
    {
      id: "2",
      title: "Wizardry Summit",
      imageUrl: "https://via.placeholder.com/150",
      date: "2023-06-15",
      location: "Durmstrang",
      organizer: "Grindelwald",
      spellCategory: "Dark Arts",
      Fee: "75",
      description: "A summit to discuss advanced dark magic.",
      currentParticipants: 40,
      maxParticipants: 150,
    },
    {
      id: "3",
      title: "Quidditch Tournament",
      imageUrl: "https://via.placeholder.com/150",
      date: "2023-07-20",
      location: "The Burrow",
      organizer: "Weasley Family",
      spellCategory: "Sports",
      Fee: "25",
      description: "An exciting Quidditch tournament open to all witches and wizards.",
      currentParticipants: 15,
      maxParticipants: 50,
    },
    {
      id: "4",
      title: "Potion Brewing Workshop",
      imageUrl: "https://via.placeholder.com/150",
      date: "2023-08-05",
      location: "Diagon Alley",
      organizer: "Madam Pomfrey",
      spellCategory: "Potion Making",
      Fee: "40",
      description: "A hands-on workshop where you'll brew your own potions.",
      currentParticipants: 10,
      maxParticipants: 30,
    },
    {
      id: "5",
      title: "Dark Arts Exhibition",
      imageUrl: "https://via.placeholder.com/150",
      date: "2023-09-12",
      location: "Knockturn Alley",
      organizer: "Death Eaters",
      spellCategory: "Dark Arts",
      Fee: "100",
      description: "A secretive exhibition showcasing the power of the dark arts.",
      currentParticipants: 5,
      maxParticipants: 20,
    },
    {
      id: "6",
      title: "Muggle Studies Conference",
      imageUrl: "https://via.placeholder.com/150",
      date: "2023-10-08",
      location: "Hogwarts",
      organizer: "Professor Binns",
      spellCategory: "Muggle Studies",
      Fee: "20",
      description: "A conference to discuss Muggle culture and history.",
      currentParticipants: 50,
      maxParticipants: 100,
    },
    {
      id: "7",
      title: "Wand Carving Masterclass",
      imageUrl: "https://via.placeholder.com/150",
      date: "2023-11-03",
      location: "Ollivanders",
      organizer: "Mr. Ollivander",
      spellCategory: "Wand Crafting",
      Fee: "60",
      description: "Learn the ancient art of wand carving from the masters.",
      currentParticipants: 20,
      maxParticipants: 30,
    },
    {
      id: "8",
      title: "Magical Creature Care Symposium",
      imageUrl: "https://via.placeholder.com/150",
      date: "2023-12-18",
      location: "Newt Scamander's Office",
      organizer: "Newt Scamander",
      spellCategory: "Magical Creatures",
      Fee: "70",
      description: "A symposium discussing the care and treatment of magical creatures.",
      currentParticipants: 10,
      maxParticipants: 50,
    },
    {
      id: "9",
      title: "Enchanted Garden Party",
      imageUrl: "https://via.placeholder.com/150",
      date: "2024-01-15",
      location: "The Forbidden Forest",
      organizer: "Professor Sprout",
      spellCategory: "Herbology",
      Fee: "30",
      description: "An outdoor garden party featuring enchanted plants and flowers.",
      currentParticipants: 25,
      maxParticipants: 60,
    },
    {
      id: "10",
      title: "Broomstick Racing Championship",
      imageUrl: "https://via.placeholder.com/150",
      date: "2024-02-07",
      location: "The Quidditch Pitch",
      organizer: "Oliver Wood",
      spellCategory: "Sports",
      Fee: "15",
      description: "Test your flying skills in the fastest broomstick race of the year.",
      currentParticipants: 40,
      maxParticipants: 80,
    },
    {
      id: "11",
      title: "Time-Turner Exhibition",
      imageUrl: "https://via.placeholder.com/150",
      date: "2024-03-20",
      location: "Ministry of Magic",
      organizer: "Professor McGonagall",
      spellCategory: "Time Magic",
      Fee: "90",
      description: "Explore the mysteries of time travel with a live exhibition.",
      currentParticipants: 50,
      maxParticipants: 100,
    },
    {
      id: "12",
      title: "Wizard's Duel Tournament",
      imageUrl: "https://via.placeholder.com/150",
      date: "2024-04-10",
      location: "Hogwarts Great Hall",
      organizer: "Professor Flitwick",
      spellCategory: "Dueling",
      Fee: "80",
      description: "The ultimate duel tournament to crown the best wizard in combat.",
      currentParticipants: 16,
      maxParticipants: 50,
    },
    {
      id: "13",
      title: "Ancient Runes Conference",
      imageUrl: "https://via.placeholder.com/150",
      date: "2024-05-14",
      location: "Hogwarts Library",
      organizer: "Professor Babbling",
      spellCategory: "Ancient Magic",
      Fee: "65",
      description: "A deep dive into ancient runes and their magical uses.",
      currentParticipants: 25,
      maxParticipants: 40,
    },
    {
      id: "14",
      title: "Magical Music Festival",
      imageUrl: "https://via.placeholder.com/150",
      date: "2024-06-01",
      location: "The Leaky Cauldron",
      organizer: "The Weird Sisters",
      spellCategory: "Music & Magic",
      Fee: "50",
      description: "A magical concert featuring the most famous wizarding band.",
      currentParticipants: 60,
      maxParticipants: 200,
    },
    {
      id: "15",
      title: "Alchemy Symposium",
      imageUrl: "https://via.placeholder.com/150",
      date: "2024-07-03",
      location: "The Cauldron",
      organizer: "Nicholas Flamel",
      spellCategory: "Alchemy",
      Fee: "110",
      description: "A gathering of the most skilled alchemists to share their knowledge.",
      currentParticipants: 15,
      maxParticipants: 25,
    },
  ];
  
    

  